#! /bin/bash
mysql -u root -p"password" -e "select user, host from mysql.user;" | tail -n +2  > mysql_users

while read line
do
    echo ""
    user="$(echo $line | cut -d " " -f 1)"
    host="$(echo $line | cut -d " " -f 2)"
    mysql -u root -p"Raul755-" -e "show grants for '$user'@'$host';"
    echo ""
done < /root/mysql_users

rm -f mysql_users
